server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cubectl_identity}
    username: ${SPRING_DATASOURCE_USERNAME:cubectl}
    password: ${SPRING_DATASOURCE_PASSWORD:cubectl}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:
    - org.cubectl.identity
  open-api:
    info:
      title: Cubectl Auth API
      version: v1
      description: Identity, JWT authentication, users, roles and permissions API

management:
  endpoints:
    web:
      exposure:
        include: health,info

cubectl:
  jwt:
    issuer: ${CUBECTL_JWT_ISSUER:cubectl-auth}
    secret: ${CUBECTL_JWT_SECRET:dev-only-change-this-secret-dev-only-change-this-secret}
    access-token-ttl: ${CUBECTL_ACCESS_TOKEN_TTL:PT15M}
    refresh-token-ttl: ${CUBECTL_REFRESH_TOKEN_TTL:P30D}
